#include "QueueVector.h"

void test01();

int main() {
	test01();
	return 0;
}
void test01() {

	std::cout << '\n' << '\n' << '\n';
	std::cout << "			" << " ######## " << "	" << "   ##   " << '\n';
	std::cout << "			" << "##      ##" << "	" << "  ###   " << '\n';
	std::cout << "			" << "##      ##" << "	" << " # ##   " << '\n';
	std::cout << "			" << "##      ##" << "	" << "   ##   " << '\n';
	std::cout << "			" << "##      ##" << "	" << "   ##   " << '\n';
	std::cout << "			" << " ######## " << "	" << "  ####  " << '\n';
	std::cout << '\n' << '\n' << '\n';

	////////////////////////////////////////////////////////////////////

	QueueVector<int> queue;
	QueueVector<int> queue1;
	queue1.print();
	queue1.deQueue();
	queue.enQueue(1);
	queue.print();
	queue.enQueue(2);
	queue.print();
	queue.enQueue(3);
	queue.print();
	queue.enQueue(4);
	queue.print();
	queue.enQueue(5);
	queue.print();
	queue.enQueue(6);
	queue.print();
	queue.enQueue(7);
	queue.print();
	queue.enQueue(8);
	queue.print();
	queue.enQueue(9);
	queue.print();
	queue.enQueue(10);
	queue.print();
	queue.deQueue();
	queue.print();
	queue.enQueue(11);
	queue.print();
	queue.enQueue(12);
	queue.print();
	queue.enQueue(1);
	queue.print();
	queue.enQueue(2);
	queue.print();
	queue.enQueue(3);
	queue.print();
	queue.enQueue(4);
	queue.print();
	queue.enQueue(5);
	queue.print();
	queue.enQueue(6);
	queue.print();
	queue.enQueue(7);
	queue.print();
	queue.enQueue(8);
	queue.print();
	queue.enQueue(9);
	queue.print();
	queue.enQueue(10);
	queue.print();
	queue.deQueue();
	queue.print();
	queue.enQueue(11);
	queue.print();
	queue.enQueue(12);
	queue.print();
	queue.enQueue(1);
	queue.print();
	queue.enQueue(2);
	queue.print();
	queue.enQueue(3);
	queue.print();
	queue.enQueue(4);
	queue.print();
	queue.enQueue(5);
	queue.print();
	queue.enQueue(6);
	queue.print();
	queue.enQueue(7);
	queue.print();
	queue.enQueue(8);
	queue.print();
	queue.enQueue(9);
	queue.print();
	queue.enQueue(10);
	queue.print();
	queue.deQueue();
	queue.print();
	queue.enQueue(11);
	queue.print();
	queue.enQueue(12);
	queue.print();
	queue.enQueue(1);
	queue.print();
	queue.enQueue(2);
	queue.print();
	queue.enQueue(3);
	queue.print();
	queue.enQueue(4);
	queue.print();
	queue.enQueue(5);
	queue.print();
	queue.enQueue(6);
	queue.print();
	queue.enQueue(7);
	queue.print();
	queue.enQueue(8);
	queue.print();
	queue.enQueue(9);
	queue.print();
	queue.enQueue(10);
	queue.print();
	queue.deQueue();
	queue.print();
	queue.enQueue(11);
	queue.print();
	queue.enQueue(12);
	queue.print();
	queue.enQueue(1);
	queue.print();
	queue.enQueue(2);
	queue.print();
	queue.enQueue(3);
	queue.print();
	queue.enQueue(4);
	queue.print();
	queue.enQueue(5);
	queue.print();
	queue.enQueue(6);
	queue.print();
	queue.enQueue(7);
	queue.print();
	queue.enQueue(8);
	queue.print();
	queue.enQueue(9);
	queue.print();
	queue.enQueue(10);
	queue.print();
	queue.deQueue();
	queue.print();
	queue.enQueue(11);
	queue.print();
	queue.enQueue(12);
	queue.print();
	queue.enQueue(1);
	queue.print();
	queue.enQueue(2);
	queue.print();
	queue.enQueue(3);
	queue.print();
	queue.enQueue(4);
	queue.print();
	queue.enQueue(5);
	queue.print();
	queue.enQueue(6);
	queue.print();
	queue.enQueue(7);
	queue.print();
	queue.enQueue(8);
	queue.print();
	queue.enQueue(9);
	queue.print();
	queue.enQueue(10);
	queue.print();
	queue.deQueue();
	queue.print();
	queue.enQueue(11);
	queue.print();
	queue.enQueue(12);
	queue.print();
	queue.enQueue(1);
	queue.print();
	queue.enQueue(2);
	queue.print();
	queue.enQueue(3);
	queue.print();
	queue.enQueue(4);
	queue.print();
	queue.enQueue(5);
	queue.print();
	queue.enQueue(6);
	queue.print();
	queue.enQueue(7);
	queue.print();
	queue.enQueue(8);
	queue.print();
	queue.enQueue(9);
	queue.print();
	queue.enQueue(10);
	queue.print();
	queue.deQueue();
	queue.print();
	queue.enQueue(11);
	queue.print();
	queue.enQueue(12);
	queue.print();
	queue.enQueue(9);
	queue.print();
	queue.enQueue(10);
	queue.print();
	queue.deQueue();
	queue.print();
	queue.enQueue(11);
	queue.print();
	queue.enQueue(12);
	queue.print();
	queue.enQueue(12);
	queue.print();

	std::cout << "----------------------------------------------" << '\n';
}